services:
  nginx:
    container_name: ng
    image: nginx:mainline
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - my-network

  app:
    container_name: app
    build: 
      context: .
    expose:
      - 8000
    networks:
      - my-network


networks:
  my-network: